public class CountryLoaders {

    public static void loadNorthAndCentralAmerica(Quiz<String, String> quiz) {
        quiz.add("Antigua and Barbuda", "Saint John's");
        quiz.add("Barbados", "Bridgetown");
        quiz.add("Belize", "Belmopan");
        quiz.add("Canada", "Ottawa");
        quiz.add("Costa Rica", "San Jose");
        quiz.add("Cuba", "Havana");
        quiz.add("Dominica", "Roseau");
        quiz.add("Dominican Republic", "Santo Domingo");
        quiz.add("El Salvador", "San Salvador");
        quiz.add("Grenada", "St. George's");
        quiz.add("Guatemala", "Guatemala City");
        quiz.add("Haiti", "Port-au-Prince");
        quiz.add("Honduras", "Tegucigalpa");
        quiz.add("Jamaica", "Kingston");
        quiz.add("Mexico", "Mexico City");
        quiz.add("Nicaragua", "Managua");
        quiz.add("Panama", "Panama City");
        quiz.add("Saint Kitts and Nevis", "Basseterre");
        quiz.add("Saint Lucia", "Castries");
        quiz.add("Saint Vincent and the Grenadines", "Kingstown");
        quiz.add("Trinidad and Tobago", "Port of Spain");
        quiz.add("United States", "Washington D.C.");
    }

    public static void loadSouthAmerica(Quiz<String, String> quiz) {
        quiz.add("Argentina", "Buenos Aires");
        quiz.add("Brazil", "Brasilia");
        quiz.add("Chile", "Santiago");
        quiz.add("Colombia", "Bogota");
        quiz.add("Ecuador", "Quito");
        quiz.add("Guyana", "Georgetown");
        quiz.add("Paraguay", "Asuncion");
        quiz.add("Peru", "Lima");
        quiz.add("Suriname", "Paramaribo");
        quiz.add("Uruguay", "Montevideo");
    }

    public static void loadEurope(Quiz<String, String> quiz) {
        quiz.add("Albania", "Tirana");
        quiz.add("Austria", "Vienna");
        quiz.add("Belarus", "Minsk");
        quiz.add("Belgium", "Brussels");
        quiz.add("Bosnia and Herzegovina", "Sarajevo");
        quiz.add("Bulgaria", "Sofia");
        quiz.add("Croatia", "Zagreb");
        quiz.add("Cyprus", "Nicosia");
        quiz.add("Denmark", "Copenhagen");
        quiz.add("Estonia", "Tallinn");
        quiz.add("Faroe Islands", "Torshavn");
        quiz.add("Finland", "Helsinki");
        quiz.add("France", "Paris");
        quiz.add("Germany", "Berlin");
        quiz.add("Gibraltar", "Gibraltar");
        quiz.add("Greece", "Athens");
        quiz.add("Guernsey", "St. Peter Port");
        quiz.add("Hungary", "Budapest");
        quiz.add("Iceland", "Reykjavik");
        quiz.add("Ireland", "Dublin");
        quiz.add("Isle of Man", "Douglas");
        quiz.add("Italy", "Rome");
        quiz.add("Jersey", "Saint Helier");
        quiz.add("Latvia", "Riga");
        quiz.add("Liechtenstein", "Vaduz");
        quiz.add("Lithuania", "Vilnius");
        quiz.add("Luxembourg", "Luxembourg");
        quiz.add("Malta", "Valletta");
        quiz.add("Monaco", "Monaco");
        quiz.add("Netherlands", "Amsterdam");
        quiz.add("Norway", "Oslo");
        quiz.add("Poland", "Warsaw");
        quiz.add("Portugal", "Lisbon");
        quiz.add("Romania", "Bucharest");
        quiz.add("Russia", "Moscow");
        quiz.add("San Marino", "City of San Marino");
        quiz.add("Serbia", "Belgrade");
        quiz.add("Slovakia", "Bratislava");
        quiz.add("Slovenia", "Ljubljana");
        quiz.add("Spain", "Madrid");
        quiz.add("Svalbard and Jan Mayen", "Longyearbyen");
        quiz.add("Sweden", "Stockholm");
        quiz.add("Switzerland", "Bern");
        quiz.add("Ukraine", "Kiev");
        quiz.add("United Kingdom", "London");
    }

    public static void loadAfrica(Quiz<String, String> quiz) {
        quiz.add("Algeria", "Algiers");
        quiz.add("Angola", "Luanda");
        quiz.add("Benin", "Porto-Novo");
        quiz.add("Botswana", "Gaborone");
        quiz.add("British Indian Ocean Territory", "Diego Garcia");
        quiz.add("Burkina Faso", "Ouagadougou");
        quiz.add("Burundi", "Bujumbura");
        quiz.add("Cameroon", "Yaounde");
        quiz.add("Central African Republic", "Bangui");
        quiz.add("Chad", "N'Djamena");
        quiz.add("Comoros", "Moroni");
        quiz.add("Djibouti", "Djibouti");
        quiz.add("Egypt", "Cairo");
        quiz.add("Equatorial Guinea", "Malabo");
        quiz.add("Eritrea", "Asmara");
        quiz.add("Ethiopia", "Addis Ababa");
        quiz.add("Gabon", "Libreville");
        quiz.add("Ghana", "Accra");
        quiz.add("Guinea", "Conakry");
        quiz.add("Guinea-Bissau", "Bissau");
        quiz.add("Kenya", "Nairobi");
        quiz.add("Lesotho", "Maseru");
        quiz.add("Liberia", "Monrovia");
        quiz.add("Libya", "Tripoli");
        quiz.add("Madagascar", "Antananarivo");
        quiz.add("Malawi", "Lilongwe");
        quiz.add("Mali", "Bamako");
        quiz.add("Mauritania", "Nouakchott");
        quiz.add("Mauritius", "Port Louis");
        quiz.add("Mayotte", "Mamoudzou");
        quiz.add("Morocco", "Rabat");
        quiz.add("Mozambique", "Maputo");
        quiz.add("Namibia", "Windhoek");
        quiz.add("Niger", "Niamey");
        quiz.add("Nigeria", "Abuja");
        quiz.add("Rwanda", "Kigali");
        quiz.add("Réunion", "Saint-Denis");
        quiz.add("Senegal", "Dakar");
        quiz.add("Seychelles", "Victoria");
        quiz.add("Sierra Leone", "Freetown");
        quiz.add("Somalia", "Mogadishu");
        quiz.add("South Africa", "Pretoria");
        quiz.add("South Sudan", "Juba");
        quiz.add("Sudan", "Khartoum");
        quiz.add("Togo", "Lomé");
        quiz.add("Tunisia", "Tunis");
        quiz.add("Uganda", "Kampala");
        quiz.add("Western Sahara", "El Aaiun");
        quiz.add("Zambia", "Lusaka");
        quiz.add("Zimbabwe", "Harare");
    }

    public static void loadAsia(Quiz<String, String> quiz) {
        quiz.add("Afghanistan", "Kabul");
        quiz.add("Armenia", "Yerevan");
        quiz.add("Azerbaijan", "Baku");
        quiz.add("Bahrain", "Manama");
        quiz.add("Bangladesh", "Dhaka");
        quiz.add("Bhutan", "Thimphu");
        quiz.add("Cambodia", "Phnom Penh");
        quiz.add("China", "Beijing");
        quiz.add("Georgia", "Tbilisi");
        quiz.add("Hong Kong", "City of Victoria");
        quiz.add("India", "New Delhi");
        quiz.add("Indonesia", "Jakarta");
        quiz.add("Iraq", "Baghdad");
        quiz.add("Israel", "Jerusalem");
        quiz.add("Japan", "Tokyo");
        quiz.add("Jordan", "Amman");
        quiz.add("Kazakhstan", "Astana");
        quiz.add("Kuwait", "Kuwait City");
        quiz.add("Kyrgyzstan", "Bishkek");
        quiz.add("Lao People's Democratic Republic", "Vientiane");
        quiz.add("Lebanon", "Beirut");
        quiz.add("Malaysia", "Kuala Lumpur");
        quiz.add("Maldives", "Male");
        quiz.add("Mongolia", "Ulan Bator");
        quiz.add("Nepal", "Kathmandu");
        quiz.add("Oman", "Muscat");
        quiz.add("Pakistan", "Islamabad");
        quiz.add("Philippines", "Manila");
        quiz.add("Qatar", "Doha");
        quiz.add("Saudi Arabia", "Riyadh");
        quiz.add("Singapore", "Singapore");
        quiz.add("Sri Lanka", "Colombo");
        quiz.add("Syrian Arab Republic", "Damascus");
        quiz.add("Tajikistan", "Dushanbe");
        quiz.add("Thailand", "Bangkok");
        quiz.add("Turkey", "Ankara");
        quiz.add("Turkmenistan", "Ashgabat");
        quiz.add("United Arab Emirates", "Abu Dhabi");
        quiz.add("Uzbekistan", "Tashkent");
        quiz.add("Yemen", "Sana'a");
    }

    public static void loadOceania(Quiz<String, String> quiz) {
        quiz.add("American Samoa", "Pago Pago");
        quiz.add("Australia", "Canberra");
        quiz.add("Christmas Island", "Flying Fish Cove");
        quiz.add("Cocos (Keeling) Islands", "West Island");
        quiz.add("Cook Islands", "Avarua");
        quiz.add("Fiji", "Suva");
        quiz.add("French Polynesia", "Papeete");
        quiz.add("Guam", "Hagatna");
        quiz.add("Kiribati", "South Tarawa");
        quiz.add("Marshall Islands", "Majuro");
        quiz.add("Nauru", "Yaren");
        quiz.add("New Caledonia", "Noumea");
        quiz.add("New Zealand", "Wellington");
        quiz.add("Niue", "Alofi");
        quiz.add("Norfolk Island", "Kingston");
        quiz.add("Northern Mariana Islands", "Saipan");
        quiz.add("Palau", "Ngerulmud");
        quiz.add("Papua New Guinea", "Port Moresby");
        quiz.add("Samoa", "Apia");
        quiz.add("Solomon Islands", "Honiara");
        quiz.add("Tokelau", "Fakaofo");
        quiz.add("Tonga", "Nuku'alofa");
        quiz.add("Tuvalu", "Funafuti");
        quiz.add("Vanuatu", "Port Vila");
        quiz.add("Wallis and Futuna", "Mata-Utu");
    }

    public static void loadWorld(Quiz<String, String> quiz) {
        quiz.add("Afghanistan", "Kabul");
        quiz.add("Albania", "Tirana");
        quiz.add("Algeria", "Algiers");
        quiz.add("American Samoa", "Pago Pago");
        quiz.add("Angola", "Luanda");
        quiz.add("Anguilla", "The Valley");
        quiz.add("Antigua and Barbuda", "Saint John's");
        quiz.add("Argentina", "Buenos Aires");
        quiz.add("Armenia", "Yerevan");
        quiz.add("Aruba", "Oranjestad");
        quiz.add("Australia", "Canberra");
        quiz.add("Austria", "Vienna");
        quiz.add("Azerbaijan", "Baku");
        quiz.add("Bahrain", "Manama");
        quiz.add("Bangladesh", "Dhaka");
        quiz.add("Barbados", "Bridgetown");
        quiz.add("Belarus", "Minsk");
        quiz.add("Belgium", "Brussels");
        quiz.add("Belize", "Belmopan");
        quiz.add("Benin", "Porto-Novo");
        quiz.add("Bermuda", "Hamilton");
        quiz.add("Bhutan", "Thimphu");
        quiz.add("Bosnia and Herzegovina", "Sarajevo");
        quiz.add("Botswana", "Gaborone");
        quiz.add("Brazil", "Brasilia");
        quiz.add("British Indian Ocean Territory", "Diego Garcia");
        quiz.add("Bulgaria", "Sofia");
        quiz.add("Burkina Faso", "Ouagadougou");
        quiz.add("Burundi", "Bujumbura");
        quiz.add("Cambodia", "Phnom Penh");
        quiz.add("Cameroon", "Yaounde");
        quiz.add("Canada", "Ottawa");
        quiz.add("Cayman Islands", "George Town");
        quiz.add("Central African Republic", "Bangui");
        quiz.add("Chad", "N'Djamena");
        quiz.add("Chile", "Santiago");
        quiz.add("China", "Beijing");
        quiz.add("Christmas Island", "Flying Fish Cove");
        quiz.add("Cocos (Keeling) Islands", "West Island");
        quiz.add("Colombia", "Bogota");
        quiz.add("Comoros", "Moroni");
        quiz.add("Cook Islands", "Avarua");
        quiz.add("Costa Rica", "San Jose");
        quiz.add("Croatia", "Zagreb");
        quiz.add("Cuba", "Havana");
        quiz.add("Cyprus", "Nicosia");
        quiz.add("Denmark", "Copenhagen");
        quiz.add("Djibouti", "Djibouti");
        quiz.add("Dominica", "Roseau");
        quiz.add("Dominican Republic", "Santo Domingo");
        quiz.add("Ecuador", "Quito");
        quiz.add("Egypt", "Cairo");
        quiz.add("El Salvador", "San Salvador");
        quiz.add("Equatorial Guinea", "Malabo");
        quiz.add("Eritrea", "Asmara");
        quiz.add("Estonia", "Tallinn");
        quiz.add("Ethiopia", "Addis Ababa");
        quiz.add("Faroe Islands", "Torshavn");
        quiz.add("Fiji", "Suva");
        quiz.add("Finland", "Helsinki");
        quiz.add("France", "Paris");
        quiz.add("French Guiana", "Cayenne");
        quiz.add("French Polynesia", "Papeete");
        quiz.add("Gabon", "Libreville");
        quiz.add("Georgia", "Tbilisi");
        quiz.add("Germany", "Berlin");
        quiz.add("Ghana", "Accra");
        quiz.add("Gibraltar", "Gibraltar");
        quiz.add("Greece", "Athens");
        quiz.add("Greenland", "Nuuk");
        quiz.add("Grenada", "St. George's");
        quiz.add("Guadeloupe", "Basse-Terre");
        quiz.add("Guam", "Hagatna");
        quiz.add("Guatemala", "Guatemala City");
        quiz.add("Guernsey", "St. Peter Port");
        quiz.add("Guinea", "Conakry");
        quiz.add("Guinea-Bissau", "Bissau");
        quiz.add("Guyana", "Georgetown");
        quiz.add("Haiti", "Port-au-Prince");
        quiz.add("Honduras", "Tegucigalpa");
        quiz.add("Hong Kong", "City of Victoria");
        quiz.add("Hungary", "Budapest");
        quiz.add("Iceland", "Reykjavik");
        quiz.add("India", "New Delhi");
        quiz.add("Indonesia", "Jakarta");
        quiz.add("Iraq", "Baghdad");
        quiz.add("Ireland", "Dublin");
        quiz.add("Isle of Man", "Douglas");
        quiz.add("Israel", "Jerusalem");
        quiz.add("Italy", "Rome");
        quiz.add("Jamaica", "Kingston");
        quiz.add("Japan", "Tokyo");
        quiz.add("Jersey", "Saint Helier");
        quiz.add("Jordan", "Amman");
        quiz.add("Kazakhstan", "Astana");
        quiz.add("Kenya", "Nairobi");
        quiz.add("Kiribati", "South Tarawa");
        quiz.add("Kuwait", "Kuwait City");
        quiz.add("Kyrgyzstan", "Bishkek");
        quiz.add("Lao People's Democratic Republic", "Vientiane");
        quiz.add("Latvia", "Riga");
        quiz.add("Lebanon", "Beirut");
        quiz.add("Lesotho", "Maseru");
        quiz.add("Liberia", "Monrovia");
        quiz.add("Libya", "Tripoli");
        quiz.add("Liechtenstein", "Vaduz");
        quiz.add("Lithuania", "Vilnius");
        quiz.add("Luxembourg", "Luxembourg");
        quiz.add("Madagascar", "Antananarivo");
        quiz.add("Malawi", "Lilongwe");
        quiz.add("Malaysia", "Kuala Lumpur");
        quiz.add("Maldives", "Male");
        quiz.add("Mali", "Bamako");
        quiz.add("Malta", "Valletta");
        quiz.add("Marshall Islands", "Majuro");
        quiz.add("Martinique", "Fort-de-France");
        quiz.add("Mauritania", "Nouakchott");
        quiz.add("Mauritius", "Port Louis");
        quiz.add("Mayotte", "Mamoudzou");
        quiz.add("Mexico", "Mexico City");
        quiz.add("Monaco", "Monaco");
        quiz.add("Mongolia", "Ulan Bator");
        quiz.add("Montserrat", "Plymouth");
        quiz.add("Morocco", "Rabat");
        quiz.add("Mozambique", "Maputo");
        quiz.add("Namibia", "Windhoek");
        quiz.add("Nauru", "Yaren");
        quiz.add("Nepal", "Kathmandu");
        quiz.add("Netherlands", "Amsterdam");
        quiz.add("New Caledonia", "Noumea");
        quiz.add("New Zealand", "Wellington");
        quiz.add("Nicaragua", "Managua");
        quiz.add("Niger", "Niamey");
        quiz.add("Nigeria", "Abuja");
        quiz.add("Niue", "Alofi");
        quiz.add("Norfolk Island", "Kingston");
        quiz.add("Northern Mariana Islands", "Saipan");
        quiz.add("Norway", "Oslo");
        quiz.add("Oman", "Muscat");
        quiz.add("Pakistan", "Islamabad");
        quiz.add("Palau", "Ngerulmud");
        quiz.add("Panama", "Panama City");
        quiz.add("Papua New Guinea", "Port Moresby");
        quiz.add("Paraguay", "Asuncion");
        quiz.add("Peru", "Lima");
        quiz.add("Philippines", "Manila");
        quiz.add("Poland", "Warsaw");
        quiz.add("Portugal", "Lisbon");
        quiz.add("Puerto Rico", "San Juan");
        quiz.add("Qatar", "Doha");
        quiz.add("Romania", "Bucharest");
        quiz.add("Russian Federation", "Moscow");
        quiz.add("Rwanda", "Kigali");
        quiz.add("Réunion", "Saint-Denis");
        quiz.add("Saint Kitts and Nevis", "Basseterre");
        quiz.add("Saint Lucia", "Castries");
        quiz.add("Saint Pierre and Miquelon", "Saint-Pierre");
        quiz.add("Saint Vincent and the Grenadines", "Kingstown");
        quiz.add("Samoa", "Apia");
        quiz.add("San Marino", "City of San Marino");
        quiz.add("Saudi Arabia", "Riyadh");
        quiz.add("Senegal", "Dakar");
        quiz.add("Serbia", "Belgrade");
        quiz.add("Seychelles", "Victoria");
        quiz.add("Sierra Leone", "Freetown");
        quiz.add("Singapore", "Singapore");
        quiz.add("Slovakia", "Bratislava");
        quiz.add("Slovenia", "Ljubljana");
        quiz.add("Solomon Islands", "Honiara");
        quiz.add("Somalia", "Mogadishu");
        quiz.add("South Africa", "Pretoria");
        quiz.add("South Georgia and the South Sandwich Islands", "King Edward Point");
        quiz.add("South Sudan", "Juba");
        quiz.add("Spain", "Madrid");
        quiz.add("Sri Lanka", "Colombo");
        quiz.add("Sudan", "Khartoum");
        quiz.add("Suriname", "Paramaribo");
        quiz.add("Svalbard and Jan Mayen", "Longyearbyen");
        quiz.add("Sweden", "Stockholm");
        quiz.add("Switzerland", "Bern");
        quiz.add("Syrian Arab Republic", "Damascus");
        quiz.add("Tajikistan", "Dushanbe");
        quiz.add("Thailand", "Bangkok");
        quiz.add("Togo", "Lomé");
        quiz.add("Tokelau", "Fakaofo");
        quiz.add("Tonga", "Nuku'alofa");
        quiz.add("Trinidad and Tobago", "Port of Spain");
        quiz.add("Tunisia", "Tunis");
        quiz.add("Turkey", "Ankara");
        quiz.add("Turkmenistan", "Ashgabat");
        quiz.add("Tuvalu", "Funafuti");
        quiz.add("Uganda", "Kampala");
        quiz.add("Ukraine", "Kiev");
        quiz.add("United Arab Emirates", "Abu Dhabi");
        quiz.add("United Kingdom", "London");
        quiz.add("United States", "Washington D.C.");
        quiz.add("Uruguay", "Montevideo");
        quiz.add("Uzbekistan", "Tashkent");
        quiz.add("Vanuatu", "Port Vila");
        quiz.add("Wallis and Futuna", "Mata-Utu");
        quiz.add("Western Sahara", "El Aaiun");
        quiz.add("Yemen", "Sana'a");
        quiz.add("Zambia", "Lusaka");
        quiz.add("Zimbabwe", "Harare");
    }

}